import React,{createContext,useContext,useEffect,useRef,useState} from 'react'
import {Button,Empty,Tabs,Field,Upload,validURL,validScore} from './ui.jsx'
const SubmissionContext=createContext(null)
export default function CardView({challenge,cardId,command,act,busy,onBack,refreshKey}){
 const [data,setData]=useState(null),[tab,setTab]=useState('brief'),[people,setPeople]=useState(null),[person,setPerson]=useState(null),[entries,setEntries]=useState([]),[score,setScore]=useState(''),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(false)
 const query={challenge:challenge.id,card:cardId};const loadVersion=useRef(0)
 async function load(){const version=++loadVersion.current;setLoading(true);setLoadError('');try{const next=await command('card',query);let nextEntries=[],nextPeople=null;if(tab==='review')nextEntries=(await command('queue',query)).submissions;if(tab==='others'||tab==='results'){nextPeople=(await command('people',query)).people;if(person)nextEntries=(await command('person',{...query,person})).submissions}if(version!==loadVersion.current)return;setData(next);setEntries(nextEntries);setPeople(nextPeople)}catch(e){if(version===loadVersion.current)setLoadError(e.message)}finally{if(version===loadVersion.current)setLoading(false)}}
 useEffect(()=>{load();return()=>{loadVersion.current++}},[cardId,tab,person,refreshKey])
 useEffect(()=>{if(tab!=='review'||!entries.some(s=>s.agent_score==null&&!s.agent_error))return;const t=setInterval(load,15000);return()=>clearInterval(t)},[tab,entries,cardId])
 if(!data)return <><Button onClick={onBack}>Back to challenge</Button>{loadError?<div className="cp-error">{loadError}<Button onClick={load}>Retry</Button></div>:<p role="status">Loading card…</p>}</>
 const card=data.card,own=data.submissions;const tabs=[['brief',data.competitor?'Requirements & my entries':'Requirements']];if(data.competitor)tabs.push(['others','See what others posted']);if(data.can_review)tabs.push(['review','Review queue']);if(data.admin)tabs.push(['results','Results / scoring'])
 const approved=entries.filter(s=>s.status==='approved');const currentScore=people?.find(x=>x.handle===person)?.score
 async function change(action,body,msg){const ok=await act(action,{...query,...body},msg);return ok}
 return <SubmissionContext.Provider value={{command,query}}><><Button onClick={onBack}>Back to challenge</Button><section className="cp-section"><div className="cp-eyebrow">Challenge card</div><h1>{card.name}</h1><div className="cp-row"><span className="cp-tag">{card.review==='agent'?'AI reference + admin decision':'Human review'}</span><span className="cp-tag">{card.cap===null?'Unlimited submissions':`${card.cap} submissions per competitor`}</span></div></section><Tabs items={tabs} value={tab} onChange={v=>{setTab(v);setPerson(null);setEntries([]);setPeople(null);setScore('')}}/>{loadError&&<div className="cp-error" role="alert">{loadError}<Button onClick={load}>Retry</Button></div>}
 {tab==='brief'&&<><section className="cp-panel"><h2>Requirements</h2><div className="cp-requirements">{card.requirements}</div>{data.admin&&card.review==='human'&&<p className="cp-muted">Reviewers: {card.reviewers.join(', ')}</p>}</section>{data.competitor&&<><section className="cp-section"><h2>Your submissions</h2>{own.length?<div className="cp-stack">{own.map(s=><Submission key={s.id} submission={s}/>)}</div>:<Empty title="Your first entry starts here">Read the requirements, then use the form below to submit your work.</Empty>}</section><section className="cp-section">{data.can_submit&&(card.cap===null||own.length<card.cap)?<Submit card={card} count={own.length} busy={busy} onSubmit={values=>change('submit',{values},'Submitted. Your entry is now waiting for review.')}/>:<div className="cp-notice">{card.cap!==null&&own.length>=card.cap?'You have reached this card’s submission limit. Rejected entries still count.':'Submissions are available only while the challenge is open, between its start and end dates.'}</div>}</section></>}</>}
 {(tab==='others'||tab==='results')&&<section>{person?<><Button onClick={()=>{setPerson(null);setEntries([]);setScore('')}}>Back to all competitors</Button><h2 className="cp-section">{person}</h2><div className="cp-stack">{loading?<p role="status">Loading submissions…</p>:entries.length?entries.map(s=><Submission key={s.id} submission={s} reference={tab==='results'}/>):<Empty title="No submissions yet">This competitor has not submitted to this card. Choose another competitor from the list.</Empty>}</div>{tab==='results'&&<form className="cp-panel cp-form cp-section" onSubmit={async e=>{e.preventDefault();if(await change('score',{person,score},'Official card score saved.'))setScore('')}}><h3>Official card score</h3><div className="cp-muted">Current: {currentScore==null?'Pending':currentScore.toFixed(1)}. Judge the competitor’s approved submissions as a whole. Rejected and pending entries do not count.</div><Field label="Score, 0.0–10.0" hint="At most one decimal place, for example 5.7."><input className="cp-input" inputMode="decimal" value={score} onChange={e=>setScore(e.target.value)} placeholder="5.7"/>{score&&!validScore(score)&&<span className="cp-error">Enter 0.0–10.0 with at most one decimal.</span>}</Field>{!approved.length&&<div className="cp-hint">Approve at least one submission before entering an official score.</div>}<Button primary disabled={busy||!validScore(score)||!approved.length}>Save official score</Button></form>}</>:<><h2>{tab==='others'?'See what others posted':'Choose a competitor'}</h2><p className="cp-muted">{tab==='others'?'Choose someone to see their entries on this card. This view has no scoring controls.':'Open a competitor’s submissions and enter one official score for this card.'}</p>{people===null?<p role="status">Loading competitors…</p>:people.length?<div className="cp-list">{people.map(p=><button className="cp-listitem" key={p.handle} onClick={()=>setPerson(p.handle)}><strong>{p.handle}</strong><p>{p.count} submissions{tab==='results'?` · Score: ${p.score==null?'Pending':p.score.toFixed(1)}`:''}</p></button>)}</div>:<Empty title="No competitors yet">Add competitors at the challenge level before reviewing results.</Empty>}</>}</section>}
 {tab==='review'&&<section><div className="cp-row cp-between"><h2>Pending submissions</h2><Button onClick={load}>Refresh</Button></div>{card.review==='human'&&<p className="cp-muted">All assigned reviewers must approve; any rejection rejects. This does not assign an official score.</p>}{loading?<p role="status">Loading review queue…</p>:entries.length?<div className="cp-stack">{entries.map(s=><ReviewEntry key={s.id} s={s} card={card} busy={busy} change={change} canDecide={data.can_decide}/>)}</div>:<Empty title="Nothing waiting for review">New submissions appear here. Refresh to check for entries from competitors.</Empty>}</section>}
 </></SubmissionContext.Provider>
}
export function Submission({submission,reference=false}){const ctx=useContext(SubmissionContext);const [full,setFull]=useState(null),[error,setError]=useState('');const s=full?{...full,...submission}:submission;async function expand(){try{setFull(await ctx.command('submission',{...ctx.query,submission:s.id}));setError('')}catch(e){setError(e.message)}}return <article className="cp-panel"><div className="cp-row cp-between"><span className={`cp-tag ${s.status}`}>{s.status==='pending'?'Pending review':s.status==='approved'?'Approved':'Rejected'}</span><span className="cp-hint">{new Date(s.created_at).toLocaleString()}</span></div>{!s.values&&<div className="cp-section"><Button onClick={expand}>View submission</Button>{error&&<p role="alert" className="cp-error">{error}</p>}</div>}{Object.entries(s.values||{}).map(([kind,v])=><section className="cp-section" key={kind}>{kind==='text'?<div className="cp-pre">{v}</div>:kind==='link'?<a className="cp-link" href={v} target="_blank" rel="noopener noreferrer">{v}</a>:kind==='image'?<img className="cp-image" src={v.data} alt={v.name}/>:kind==='pr'?<><a className="cp-link" href={v.url} target="_blank" rel="noopener noreferrer">Open pull request</a><div className="cp-grid two"><div><h3>Before</h3><img className="cp-image" src={v.before.data} alt={v.before.name}/></div><div><h3>After</h3><img className="cp-image" src={v.after.data} alt={v.after.name}/></div></div></>:null}</section>)}{reference&&s.agent_score!=null&&<div className="cp-notice cp-section"><strong>Agent reference: {s.agent_score.toFixed(1)} / 10</strong><p>{s.agent_rationale}</p><span className="cp-hint">Advisory only. Not an official card score.</span></div>}{s.comment&&<p className="cp-muted">Review comment: {s.comment}</p>}{reference&&s.reviews&&Object.entries(s.reviews).map(([who,r])=><p className="cp-hint" key={who}>{who}: {r.decision}{r.comment?` — ${r.comment}`:''}</p>)}</article>}
function ReviewEntry({s,card,busy,change,canDecide}){const [comment,setComment]=useState('');const ready=canDecide&&(card.review==='human'||s.agent_score!=null);return <section className="cp-stack"><h3>{s.competitor}</h3><Submission submission={s} reference/>{card.review==='agent'&&s.agent_score==null&&<div className="cp-notice">{s.agent_error||'Waiting for the agent’s score and rationale. This queue refreshes while open.'}{s.agent_error&&<Button disabled={busy} onClick={()=>change('retry_agent',{submission:s.id},'Agent review queued again.')}>Retry agent review</Button>}</div>}{!canDecide&&<p className="cp-hint">Only the assigned reviewers can decide on this submission.</p>}<Field label="Review comment (optional)"><textarea className="cp-textarea" value={comment} maxLength={2000} onChange={e=>setComment(e.target.value)}/></Field><div className="cp-row"><Button primary disabled={busy||!ready} onClick={()=>change('decide',{submission:s.id,decision:'approved',comment},'Approval recorded.')}>Approve</Button><Button disabled={busy||!ready} onClick={()=>change('decide',{submission:s.id,decision:'rejected',comment},'Rejection recorded.')}>Reject</Button></div><hr className="cp-divider"/></section>}
function Submit({card,count,busy,onSubmit}){
 const [values,setValues]=useState({}),[version,setVersion]=useState(0),[confirmation,setConfirmation]=useState('')
 const complete=card.types.every(t=>t==='text'?values.text?.trim():t==='link'?validURL(values.link):t==='image'?!!values.image?.data:t==='pr'?validURL(values.pr?.url)&&values.pr?.before?.data&&values.pr?.after?.data:false)
 const field=(k,v)=>setValues(prev=>({...prev,[k]:v}));const pr=(k,v)=>setValues(prev=>({...prev,pr:{...prev.pr,[k]:v}}))
 return <form className="cp-form cp-panel" onSubmit={async e=>{e.preventDefault();if(complete&&await onSubmit(values)){setValues({});setVersion(v=>v+1);setConfirmation('Submitted successfully. Your entry is waiting for review.')}}}><h2>Submit your work</h2>{confirmation&&<div role="status" className="cp-notice">{confirmation}</div>}<p className="cp-hint">{card.cap===null?'Unlimited submissions':`${card.cap-count} submissions remaining`}. Rejected entries still count toward your limit.</p>{card.types.map(t=>t==='text'?<Field key={t} label="Text"><textarea className="cp-textarea" value={values.text||''} maxLength={20000} onChange={e=>field(t,e.target.value)} placeholder="Write your entry here…"/></Field>:t==='link'?<Field key={t} label="Link"><input className="cp-input" type="url" value={values.link||''} onChange={e=>field(t,e.target.value)} placeholder="Paste a full URL starting with https://"/>{values.link&&!validURL(values.link)&&<span className="cp-error">Enter a complete http or https link.</span>}</Field>:t==='image'?<Upload key={t+version} label="Image" value={values.image} onChange={v=>field(t,v)}/>:<div className="cp-form" key={t+version}><Field label="Pull request link"><input className="cp-input" type="url" value={values.pr?.url||''} onChange={e=>pr('url',e.target.value)} placeholder="Paste the complete pull request URL"/></Field><Upload label="Before screenshot" value={values.pr?.before} onChange={v=>pr('before',v)}/><Upload label="After screenshot" value={values.pr?.after} onChange={v=>pr('after',v)}/></div>)}<Button primary disabled={!complete||busy}>Submit for review</Button>{!complete&&<p className="cp-hint">Complete every required field before submitting.</p>}</form>
}
