import React,{useState} from 'react'
import {Button,Field,Upload,Empty} from './ui.jsx'
export function CreateChallenge({busy,onSave,onBack}){
 const [f,setF]=useState({title:'',description:'',start:'',end:'',cover:null});const valid=f.title.trim()&&f.description.trim()&&f.start&&f.end&&f.end>=f.start
 return <><Button onClick={onBack}>Back to challenges</Button><h1>Create challenge</h1><form className="cp-form cp-panel" onSubmit={e=>{e.preventDefault();if(valid)onSave(f)}}><Field label="Title"><input className="cp-input" value={f.title} maxLength={160} onChange={e=>setF({...f,title:e.target.value})} placeholder="Name your challenge" required/></Field><Field label="Description"><textarea className="cp-textarea" value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="What are people working towards?" required/></Field><div className="cp-grid two"><Field label="Start date (UTC)"><input className="cp-input" type="date" value={f.start} onChange={e=>setF({...f,start:e.target.value})} required/></Field><Field label="End date (UTC, inclusive)"><input className="cp-input" type="date" value={f.end} onChange={e=>setF({...f,end:e.target.value})} required/></Field></div>{f.end&&f.start&&f.end<f.start&&<p className="cp-error">End date must be on or after start date.</p>}<Upload label="Cover image (optional)" value={f.cover} onChange={cover=>setF({...f,cover})}/><Button primary disabled={!valid||busy} type="submit">Create draft</Button></form></>
}
export function AddCompetitor({challenge,act,busy}){
 const [who,setWho]=useState('');const valid=/^@?[a-zA-Z0-9_]{3,30}$/.test(who.trim())
 return <section className="cp-stack"><h2>Competitors</h2><p className="cp-muted">Enter someone’s @handle and they’ll get an invitation in their own Competitions app. They choose whether to accept or decline.</p><form className="cp-form cp-panel" onSubmit={async e=>{e.preventDefault();if(await act('invite',{handle:who},'Invitation sent. They can accept it from their Competitions app.'))setWho('')}}><Field label="Competitor @handle" hint="Use their unique Möbius handle. They must accept before they can submit."><input className="cp-input" value={who} onChange={e=>setWho(e.target.value)} placeholder="@handle" autoCapitalize="none" autoCorrect="off"/></Field><Button primary disabled={!valid||busy}>Send invitation</Button></form>{challenge.competitors.length?<div className="cp-list"><h3>Accepted</h3>{challenge.competitors.map(w=><div className="cp-panel" key={w}>{w}</div>)}</div>:null}{challenge.invitations?.filter(x=>x.status==='pending').length?<div className="cp-list"><h3>Waiting for a reply</h3>{challenge.invitations.filter(x=>x.status==='pending').map(x=><div className="cp-panel" key={x.id}>{x.handle}<p className="cp-muted">Invitation sent · waiting for them to accept</p></div>)}</div>:null}{!challenge.competitors.length&&!challenge.invitations?.length&&<Empty title="No competitors yet">Send the first invitation above. Accepted competitors can submit to every card.</Empty>}</section>
}
export function AddCard({types,busy,act,onBack}){
 const fresh={name:'',requirements:'',types:[],cap:'',review:'human',reviewers:'',ai_consent:false};const [f,setF]=useState(fresh)
 const capOK=f.cap===''||/^[1-9][0-9]*$/.test(f.cap)&&Number.isSafeInteger(Number(f.cap))
 const reviewers=f.reviewers.split(/[\s,]+/).filter(Boolean)
 const valid=f.name.trim()&&f.requirements.trim()&&f.types.length&&capOK&&(f.review==='agent'?f.ai_consent:reviewers.length&&reviewers.every(x=>/^@?[a-zA-Z0-9_]{3,30}$/.test(x)))
 return <><Button onClick={onBack}>Back to cards</Button><h2 className="cp-section">Add challenge card</h2><form className="cp-form cp-panel" onSubmit={async e=>{e.preventDefault();if(valid&&await act('add_card',{...f,cap:f.cap===''?null:Number(f.cap),reviewers},'Card added.'))onBack()}}><Field label="Card name"><input className="cp-input" placeholder="For example, Best Meme" maxLength={160} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Requirements" hint="Explain what competitors should submit and what makes an entry successful."><textarea className="cp-textarea" value={f.requirements} onChange={e=>setF({...f,requirements:e.target.value})} placeholder="Write the requirements for this card…"/></Field><fieldset className="cp-form"><legend>Required submission fields</legend>{Object.entries(types).map(([key,label])=><label className="cp-check" key={key}><input type="checkbox" checked={f.types.includes(key)} onChange={e=>setF({...f,types:e.target.checked?[...f.types,key]:f.types.filter(x=>x!==key)})}/>{label}</label>)}{!f.types.length&&<span className="cp-hint">Choose at least one field type.</span>}</fieldset><Field label="Maximum submissions per competitor" hint="Leave blank for unlimited. Rejected submissions still count."><input className="cp-input" inputMode="numeric" value={f.cap} placeholder="Unlimited" onChange={e=>setF({...f,cap:e.target.value})}/>{!capOK&&<span className="cp-error">Use a positive whole number, or leave blank.</span>}</Field><Field label="Who reviews submissions?"><select className="cp-select" value={f.review} onChange={e=>setF({...f,review:e.target.value})}><option value="human">Assigned human reviewers</option><option value="agent">AI agent, then admin decision</option></select></Field>{f.review==='human'?<><Field label="Reviewer Mobius IDs" hint="Separate @handles with commas. Reviewers do not need to be competitors."><input className="cp-input" value={f.reviewers} onChange={e=>setF({...f,reviewers:e.target.value})} placeholder="@reviewer"/></Field><div className="cp-notice">Every assigned reviewer must approve. Any rejection rejects the submission. Official 0–10 scores are always entered separately by the organizer.</div></>:<><div className="cp-notice">AI reviews use your Möbius model credit and include submitted images and text. Links are shown to the agent but are not automatically opened. Reviews run in the background, about one per minute. Only you can approve or reject afterward.</div><label className="cp-check"><input type="checkbox" checked={f.ai_consent} onChange={e=>setF({...f,ai_consent:e.target.checked})}/>Use my Möbius model credit to review submissions to this card.</label></>}<Button primary disabled={!valid||busy}>Add card</Button></form></>
}
