import React,{useEffect,useMemo,useRef,useState} from 'react'
import {Plus} from '@openai/apps-sdk-ui/components/Icon'
import {CSS} from './theme.js'
import {Button,Empty,Tabs,Field} from './ui.jsx'
import {CreateChallenge,AddCompetitor,AddCard} from './ChallengeForms.jsx'
import CardView from './CardView.jsx'

export default function App({appId,token}){
 const [context,setContext]=useState(null),[listing,setListing]=useState(null),[invitations,setInvitations]=useState([]),[host,setHost]=useState(''),[hostDraft,setHostDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState({page:'home'}),[challenge,setChallenge]=useState(null),[message,setMessage]=useState(''),[tab,setTab]=useState('cards'),[refreshKey,setRefreshKey]=useState(0),[board,setBoard]=useState(null)
 const navs=useRef([]),viewRef=useRef(view);viewRef.current=view
 const api=useMemo(()=>async(path,body)=>{const r=await fetch(`/api/apps/${appId}/service/${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error||d.detail||'Request failed. Please retry.');return d},[appId,token])
 const requestIds=useRef(new Map())
 const command=(action,body={},target=host,rid)=>api('command',{host:target,action,body,request_id:rid||crypto.randomUUID()})
 async function refresh(target=host){const d=await command('list',{},target);setListing(d);if(challenge&&viewRef.current.page!=='home')setChallenge(await command('challenge',{challenge:challenge.id},target));setRefreshKey(v=>v+1)}
 async function start(){setError('');try{const c=await api('context');setContext(c);setHost(c.host);const [d,pending]=await Promise.all([command('list',{},c.host),command('invitations',{},c.host)]);setListing(d);setInvitations(pending.invitations||[]);window.mobius.signal('app_ready',{item_count:d.challenges.length})}catch(e){setError(e.message)}}
 useEffect(()=>{start()},[api])
 useEffect(()=>()=>{for(const h of navs.current)h.close()},[])
 async function open(next){const previous=viewRef.current;let h;h=window.mobius.nav.open('competitions-'+next.page,{onBack:()=>{setView(previous);navs.current=navs.current.filter(x=>x!==h)},onForward:()=>{setView(next);navs.current.push(h)}});const result=await h.outcome;if(result.status==='owned'){navs.current.push(h);setView(next);setError('');setMessage('')}else setError('Could not open this view. Please try again.')}
 function back(){navs.current.pop()?.close();if(view.page==='card'||view.page==='addcard')setView({page:'challenge'});else setView({page:'home'});setError('');setMessage('')}
 async function act(action,body,msg){setBusy(true);setError('');try{const payload={...(challenge?{challenge:challenge.id}:{}),...body};const key=JSON.stringify([host,action,payload]);const rid=requestIds.current.get(key)||crypto.randomUUID();requestIds.current.set(key,rid);const result=await command(action,payload,host,rid);if(msg)setMessage(msg);await refresh();requestIds.current.delete(key);window.mobius.signal('item_created',{type:action});return result}catch(e){setError(e.message);window.mobius.signal('error',{message:e.message,source:action});return null}finally{setBusy(false)}}
 async function select(c){try{const full=await command('challenge',{challenge:c.id});setChallenge(full);setTab('cards');await open({page:'challenge'})}catch(e){setError(e.message)}}
 async function connectHost(target){setBusy(true);setError('');try{const d=await command('list',{},target);setHost(target);setListing(d);setContext(await api('context'));setMessage(d.challenges.length?'Your invited challenges are listed below.':'This organizer has not added you to an open challenge yet.');return true}catch(e){setError(e.message);return false}finally{setBusy(false)}}
 async function respond(invitation,status){setBusy(true);setError('');try{if(status==='accepted'){await command('accept_invite',{challenge:invitation.challenge,invitation_id:invitation.id},invitation.organizer_host)}else{try{await command('decline_invite',{challenge:invitation.challenge,invitation_id:invitation.id},invitation.organizer_host)}catch(e){/* local decline still removes the invitation if the organizer is offline */}}await command('respond_invitation',{invitation_id:invitation.id,status},context.host);setInvitations(v=>v.filter(x=>x.id!==invitation.id));setMessage(status==='accepted'?'Invitation accepted. Opening the challenge…':'Invitation declined.');if(status==='accepted'){await connectHost(invitation.organizer_host)}else await start()}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(tab!=='leaderboard'||!challenge)return;command('leaderboard',{challenge:challenge.id}).then(setBoard).catch(e=>setError(e.message))},[tab,challenge?.id,refreshKey])
 const hosted=context&&host===context.host
 return <div className="cp-root"><style>{CSS}</style><header className="cp-header"><span className="cp-brand">Competitions</span><span className="cp-account">{context?.identity.handle||'Your Möbius account'}</span></header><main className="cp-page">{error&&<div className="cp-error" role="alert">{error}{!context&&<Button onClick={start}>Retry connection</Button>}</div>}{message&&<div className="cp-message" role="status">{message}</div>}
 {view.page==='home'&&invitations.length>0&&<section className="cp-section"><div className="cp-eyebrow">You’re invited</div><h2>Challenge invitations</h2><p className="cp-muted">Accept an invitation to see the challenge and submit your work. Declining keeps it out of your list.</p><div className="cp-list">{invitations.map(inv=><div className="cp-panel" key={inv.id}><h3>{inv.title}</h3><p>{inv.description}</p><p className="cp-muted">From {inv.organizer} · {inv.start} – {inv.end}</p><div className="cp-row"><Button primary disabled={busy} onClick={()=>respond(inv,'accepted')}>Accept</Button><Button disabled={busy} onClick={()=>respond(inv,'declined')}>Decline</Button></div></div>)}</div></section>}
 {view.page==='home'&&<><div className="cp-eyebrow">{hosted?'Hosted by you':'Invited challenges'}</div><h1>{hosted?<>Your challenges.<br/>Their best work.</>:'Your next challenge.'}</h1><p className="cp-muted cp-intro">Create a challenge, invite competitors by their Mobius ID, and give each card a clear brief. Only people the organizer adds can take part.</p>{context&&<><Tabs items={[[context.host,'My hosted challenges'],['remote','Another organizer']]} value={hosted?context.host:'remote'} onChange={v=>v===context.host?connectHost(v):open({page:'connect'})}/><div className="cp-actions"><Button onClick={()=>refresh().catch(e=>setError(e.message))}>Refresh challenges</Button>{hosted&&<Button primary onClick={()=>open({page:'create'})}><Plus/>Create challenge</Button>}</div>{!hosted&&<p className="cp-hint">Organizer: {host}</p>}</>}{listing?<section className="cp-section">{listing.challenges.length?<div className="cp-list">{listing.challenges.map(c=><button className="cp-listitem" key={c.id} onClick={()=>select(c)}><div className="cp-row cp-between"><strong>{c.title}</strong><span className="cp-tag">{c.published?'Open':'Draft'}</span></div><p>{c.description}</p><p>{c.start} – {c.end} · {c.cards.length} cards</p></button>)}</div>:<Empty title={hosted?'No challenges yet':'No invitations yet'}>{hosted?'Create your first challenge, then add competitors and cards.':'Ask the organizer to add your Mobius ID to a challenge. You cannot join yourself.'}</Empty>}</section>:!error&&<p role="status">Connecting to your account…</p>}</>}
 {view.page==='connect'&&<><Button onClick={back}>Back to challenges</Button><h1>Open an organizer’s challenges</h1><p className="cp-muted">Use the hostname your organizer shares with you. This does not join a challenge: only their existing invitations grant access.</p><form className="cp-form cp-panel" onSubmit={async e=>{e.preventDefault();if(await connectHost(hostDraft.trim().toLowerCase()))back()}}><Field label="Organizer hostname" hint="The public address of their Möbius installation, without https:// or a path."><input className="cp-input" value={hostDraft} onChange={e=>setHostDraft(e.target.value)} placeholder="organizer.example.com" autoCapitalize="none" autoCorrect="off"/></Field><Button primary disabled={busy||!hostDraft.trim()}>Open invited challenges</Button></form>{context?.hosts?.length>0&&<section className="cp-section cp-list">{context.hosts.map(h=><Button key={h} onClick={async()=>{if(await connectHost(h))back()}}>{h}</Button>)}</section>}</>}
 {view.page==='create'&&<CreateChallenge busy={busy} onBack={back} onSave={async f=>{const c=await act('create',f,'Challenge created. Add competitors and cards next.');if(c){back();await select(c)}}}/>}
 {view.page==='challenge'&&challenge&&<><Button onClick={back}>Back to challenges</Button><section className="cp-hero cp-section">{challenge.cover&&<img className="cp-cover" src={challenge.cover.data} alt="Challenge cover"/>}<div className="cp-eyebrow">{challenge.admin?'Organizer':'Invited challenge'}</div><h1>{challenge.title}</h1><p className="cp-pre">{challenge.description}</p><div className="cp-row"><span className="cp-tag">{challenge.published?'Open':'Draft'}</span><span className="cp-hint">{challenge.start} – {challenge.end} · UTC</span></div></section><Tabs items={challenge.admin?[['cards','Cards'],['competitors','Competitors'],['leaderboard','Leaderboard'],['access','Open challenge']]:[['cards','Cards']]} value={tab} onChange={v=>{setTab(v);setBoard(null)}}/>
 {tab==='cards'&&<><div className="cp-row cp-between"><h2>Challenge cards</h2>{challenge.admin&&<Button primary onClick={()=>open({page:'addcard'})}><Plus/>Add card</Button>}</div>{challenge.cards.length?<div className="cp-list">{challenge.cards.map(c=><button className="cp-listitem" key={c.id} onClick={()=>open({page:'card',id:c.id})}><strong>{c.name}</strong><p>{c.review==='agent'?'Agent review + admin decision':'Human reviewers'} · {c.cap==null?'Unlimited entries':`${c.cap} entries per competitor`}</p></button>)}</div>:<Empty title="No cards yet">Add the first card with its requirements, fields, submission limit, and review mode.</Empty>}</>}
 {tab==='competitors'&&<AddCompetitor challenge={challenge} act={act} busy={busy}/>}
 {tab==='leaderboard'&&<><h2>Challenge leaderboard</h2><p className="cp-muted">Total = sum of entered card scores. Pending cards stay blank; they are not treated as zero. Compare the scored-card count alongside totals.</p>{board?<div className="cp-tablewrap"><table className="cp-table"><thead><tr><th>Competitor</th>{board.cards.map(c=><th key={c.id}>{c.name}</th>)}<th>Scored</th><th>Total</th></tr></thead><tbody>{board.rows.map(r=><tr key={r.handle}><td>{r.handle}</td>{board.cards.map(c=><td key={c.id}>{r.scores[c.id]==null?<span title="Pending">—</span>:r.scores[c.id].toFixed(1)}</td>)}<td>{r.scored}/{board.cards.length}</td><td>{r.total==null?'Pending':r.total.toFixed(1)}</td></tr>)}</tbody></table>{!board.rows.length&&<Empty title="No competitors to rank">Add competitors from the Competitors tab.</Empty>}</div>:<p role="status">Loading scores…</p>}</>}
 {tab==='access'&&<div className="cp-stack"><h2>Open challenge</h2><div className="cp-notice">Invitations are delivered inside each competitor’s own Competitions app. They accept or decline there, and accepted invitations open this challenge automatically.</div>{!challenge.published?<><p className="cp-muted">Add at least one card and one accepted competitor before opening this challenge. Submissions follow the start and end dates.</p><Button primary disabled={busy||!challenge.cards.length||!challenge.competitors.length} onClick={()=>act('publish',{},'Challenge opened for invited people.')}>Open challenge to invited people</Button></>:<p className="cp-muted">This challenge is open to accepted competitors. There is no public enrollment.</p>}</div>}
 </>}
 {view.page==='addcard'&&challenge&&<AddCard types={listing.field_types} busy={busy} act={act} onBack={back}/>}
 {view.page==='card'&&challenge&&<CardView key={view.id} challenge={challenge} cardId={view.id} command={command} act={act} busy={busy} onBack={back} refreshKey={refreshKey}/>}
 </main></div>
}
